// SVG 图标列表 - 从 src/assets/icons/svg 目录中获取
// 文件名（去除 .svg 扩展名）就是图标名称

const icons = [
  'axt-customer-service',
  'axt-d-database',
  'axt-d-left-top-board',
  'axt-delete',
  'axt-detail',
  'axt-edit',
  'axt-enter-right',
  'axt-exit-right',
  'axt-export',
  'axt-farm-product',
  'axt-half-s-shield',
  'axt-homepage',
  'axt-inventory',
  'axt-left-top-board',
  'axt-line-bar-chart',
  'axt-line-chart',
  'axt-location',
  'axt-menu',
  'axt-paper-search',
  'axt-people-setting',
  'axt-print',
  'axt-quit',
  'axt-rmb',
  'axt-s-close',
  'axt-s-dashboard',
  'axt-s-database',
  'axt-s-deal',
  'axt-s-down',
  'axt-s-fir-tree',
  'axt-s-id-card',
  'axt-s-location',
  'axt-s-password',
  'axt-s-record',
  'axt-s-relationship',
  'axt-s-retract',
  'axt-s-rmb',
  'axt-s-settings',
  'axt-s-up',
  'axt-s-user-board',
  'axt-s-user',
  'axt-s-write-down',
  'axt-search',
  'axt-shop',
  'axt-shopping-cart',
  'axt-shopping',
  'axt-time',
  'axt-tree-structure',
  'axt-view',
  'eye',
  'fullscreen',
  'location',
  'phone',
  'right',
  'verCode'
]

export default icons

